// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: tictactoe.proto

package tictactoe

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageResponse_State int32

const (
	MessageResponse_DRAWN        MessageResponse_State = 0
	MessageResponse_X_WINS       MessageResponse_State = 1
	MessageResponse_O_WINS       MessageResponse_State = 2
	MessageResponse_NOT_FINISHED MessageResponse_State = 3
	MessageResponse_WAITING      MessageResponse_State = 4
	MessageResponse_WAIT_TURN    MessageResponse_State = 5
	MessageResponse_INVALID      MessageResponse_State = 6
)

// Enum value maps for MessageResponse_State.
var (
	MessageResponse_State_name = map[int32]string{
		0: "DRAWN",
		1: "X_WINS",
		2: "O_WINS",
		3: "NOT_FINISHED",
		4: "WAITING",
		5: "WAIT_TURN",
		6: "INVALID",
	}
	MessageResponse_State_value = map[string]int32{
		"DRAWN":        0,
		"X_WINS":       1,
		"O_WINS":       2,
		"NOT_FINISHED": 3,
		"WAITING":      4,
		"WAIT_TURN":    5,
		"INVALID":      6,
	}
)

func (x MessageResponse_State) Enum() *MessageResponse_State {
	p := new(MessageResponse_State)
	*p = x
	return p
}

func (x MessageResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_tictactoe_proto_enumTypes[0].Descriptor()
}

func (MessageResponse_State) Type() protoreflect.EnumType {
	return &file_tictactoe_proto_enumTypes[0]
}

func (x MessageResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageResponse_State.Descriptor instead.
func (MessageResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{1, 0}
}

type MessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Init bool   `protobuf:"varint,2,opt,name=init,proto3" json:"init,omitempty"`
	Room string `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	X    int32  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y    int32  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tictactoe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageRequest) GetInit() bool {
	if x != nil {
		return x.Init
	}
	return false
}

func (x *MessageRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *MessageRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MessageRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type MessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State            MessageResponse_State `protobuf:"varint,1,opt,name=state,proto3,enum=tictactoe.MessageResponse_State" json:"state,omitempty"`
	Req              *MessageRequest       `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
	IsX              bool                  `protobuf:"varint,3,opt,name=isX,proto3" json:"isX,omitempty"`
	IsCompetitorSend bool                  `protobuf:"varint,4,opt,name=isCompetitorSend,proto3" json:"isCompetitorSend,omitempty"`
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tictactoe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tictactoe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_tictactoe_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetState() MessageResponse_State {
	if x != nil {
		return x.State
	}
	return MessageResponse_DRAWN
}

func (x *MessageResponse) GetReq() *MessageRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *MessageResponse) GetIsX() bool {
	if x != nil {
		return x.IsX
	}
	return false
}

func (x *MessageResponse) GetIsCompetitorSend() bool {
	if x != nil {
		return x.IsCompetitorSend
	}
	return false
}

var File_tictactoe_proto protoreflect.FileDescriptor

var file_tictactoe_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x22, 0x64, 0x0a, 0x0e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x6e,
	0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x79, 0x22, 0x9b, 0x02, 0x0a, 0x0f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f,
	0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2b,
	0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x74, 0x69,
	0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x72, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x73, 0x58, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x69, 0x73, 0x58, 0x12, 0x2a, 0x0a,
	0x10, 0x69, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x6e,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x73, 0x43, 0x6f, 0x6d, 0x70, 0x65,
	0x74, 0x69, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x6e, 0x64, 0x22, 0x65, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x52, 0x41, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x58, 0x5f, 0x57, 0x49, 0x4e, 0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x5f, 0x57,
	0x49, 0x4e, 0x53, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x49, 0x4e,
	0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x49, 0x54, 0x49,
	0x4e, 0x47, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x57, 0x41, 0x49, 0x54, 0x5f, 0x54, 0x55, 0x52,
	0x4e, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x06,
	0x32, 0x54, 0x0a, 0x09, 0x54, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x12, 0x47, 0x0a,
	0x0a, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x19, 0x2e, 0x74, 0x69,
	0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x69, 0x63, 0x74, 0x61, 0x63, 0x74,
	0x6f, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x69,
	0x63, 0x74, 0x61, 0x63, 0x74, 0x6f, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tictactoe_proto_rawDescOnce sync.Once
	file_tictactoe_proto_rawDescData = file_tictactoe_proto_rawDesc
)

func file_tictactoe_proto_rawDescGZIP() []byte {
	file_tictactoe_proto_rawDescOnce.Do(func() {
		file_tictactoe_proto_rawDescData = protoimpl.X.CompressGZIP(file_tictactoe_proto_rawDescData)
	})
	return file_tictactoe_proto_rawDescData
}

var file_tictactoe_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tictactoe_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tictactoe_proto_goTypes = []interface{}{
	(MessageResponse_State)(0), // 0: tictactoe.MessageResponse.State
	(*MessageRequest)(nil),     // 1: tictactoe.MessageRequest
	(*MessageResponse)(nil),    // 2: tictactoe.MessageResponse
}
var file_tictactoe_proto_depIdxs = []int32{
	0, // 0: tictactoe.MessageResponse.state:type_name -> tictactoe.MessageResponse.State
	1, // 1: tictactoe.MessageResponse.req:type_name -> tictactoe.MessageRequest
	1, // 2: tictactoe.Tictactoe.PlayStream:input_type -> tictactoe.MessageRequest
	2, // 3: tictactoe.Tictactoe.PlayStream:output_type -> tictactoe.MessageResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tictactoe_proto_init() }
func file_tictactoe_proto_init() {
	if File_tictactoe_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tictactoe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tictactoe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tictactoe_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tictactoe_proto_goTypes,
		DependencyIndexes: file_tictactoe_proto_depIdxs,
		EnumInfos:         file_tictactoe_proto_enumTypes,
		MessageInfos:      file_tictactoe_proto_msgTypes,
	}.Build()
	File_tictactoe_proto = out.File
	file_tictactoe_proto_rawDesc = nil
	file_tictactoe_proto_goTypes = nil
	file_tictactoe_proto_depIdxs = nil
}
