# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api.tictactoe_pb2 as tictactoe__pb2


class TictactoeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlayStream = channel.stream_stream(
                '/tictactoe.Tictactoe/PlayStream',
                request_serializer=tictactoe__pb2.MessageRequest.SerializeToString,
                response_deserializer=tictactoe__pb2.MessageResponse.FromString,
                )


class TictactoeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlayStream(self, request_iterator, context):
        """rpc CreateStream(Connect) returns (stream Message);
        rpc BroadcastMessage(Message) returns (Close);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TictactoeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlayStream': grpc.stream_stream_rpc_method_handler(
                    servicer.PlayStream,
                    request_deserializer=tictactoe__pb2.MessageRequest.FromString,
                    response_serializer=tictactoe__pb2.MessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tictactoe.Tictactoe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tictactoe(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlayStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/tictactoe.Tictactoe/PlayStream',
            tictactoe__pb2.MessageRequest.SerializeToString,
            tictactoe__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
